ARG GCC_X86_64_LINUX_IMAGE_NAME
from $GCC_X86_64_LINUX_IMAGE_NAME
ARG SONAR_QUBE_TOOLS_ABS_DIR
ARG SONAR_SCANNER_CLI_DOWNLOAD_URL
ARG BUILD_WRAPPER_LINUX_DOWNLOAD_URL
RUN mkdir $SONAR_QUBE_TOOLS_ABS_DIR
RUN wget $SONAR_SCANNER_CLI_DOWNLOAD_URL -P $SONAR_QUBE_TOOLS_ABS_DIR
RUN unzip $SONAR_QUBE_TOOLS_ABS_DIR/sonar-scanner-cli-4.7.0.2747-linux.zip -d $SONAR_QUBE_TOOLS_ABS_DIR
RUN rm $SONAR_QUBE_TOOLS_ABS_DIR/sonar-scanner-cli-4.7.0.2747-linux.zip
RUN wget $BUILD_WRAPPER_LINUX_DOWNLOAD_URL -P $SONAR_QUBE_TOOLS_ABS_DIR
RUN unzip $SONAR_QUBE_TOOLS_ABS_DIR/build-wrapper-linux-x86.zip -d $SONAR_QUBE_TOOLS_ABS_DIR
RUN rm $SONAR_QUBE_TOOLS_ABS_DIR/build-wrapper-linux-x86.zip
ENV PATH="${PATH}:$SONAR_QUBE_TOOLS_ABS_DIR/build-wrapper-linux-x86:/$SONAR_QUBE_TOOLS_ABS_DIR/sonar-scanner-4.7.0.2747-linux/bin"
